# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Equal Pasta'
tagline:          'Dev blog'
description:      'A blog about programming, unity, hobbies, and maybe an occasional guide.'
url:              //equalpasta.com

author:
  name:           'EqualPasta'
  url:            equalpasta@gmail.com

paginate:         4

google_analytics: UA-100824015-1

# Custom vars
version:          0.1.0
gems: [jekyll-paginate, jekyll-sitemap]

github:
  repo:           https://github.com/EqualPasta
